# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41d1938de075dc537bfa594b7863d3c74e0bc342e0a8aee70327ad31313da0f9e7f0829b4695ec2091ec19282a8c8c6026d89dbba38dc920f0c37740bfa706d6

test:
  secret_key_base: b41a13e08e830013421766a2b04dc635ebe4f719d84a98af9492c4ac0955ecc5c8bfc9817236e15c1403b7f90ce89a75962b4f949af762ef6a9b33d38c8a36d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
